version: '3'

services:

  postgres:
    image: 'postgres:14.2'
    container_name: otp-pg
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: otp-pg
